### PR TITLE
Add MLJAR AutoML

### PR DESCRIPTION
**Pull request by pplonski**
Hey!

I found your article on Reddit. I would like to submit MLJAR AutoML https://github.com/mljar/mljar-supervised 

It has some nice features:
- many algorithms
- golden features generation
- features selection
- built-in explanations
- auto-documentation
- ensembling and stacking

I've used the `03_autogluon.py` file as a starter.

I'm currently running the AutoML computation on small datasets on my local machine (12 cores 3.3 GHz).

### CODE REVIEW

**Comment by sergeyf** [comment]
Howdy. Sorry I didn't see this before today. Apparently I wasn't "Watching" my own repo for whatever reason...

I appreciate the addition. Are you able to also add the pickle file with the results to the PR? And possibly modify the code in the results notebook to include it as part of the plots?

**Comment by pplonski** [comment]
Hey @sergeyf! Sure, I will need to compute the benchmark results once again ... added a lot of features last month

**Comment by sergeyf** [comment]
Awesome, thank you! Let me know if you have any questions about adding the rest of the stuff.

**Comment by sergeyf** [comment]
Looks fantastic, thanks!

**Comment by pplonski** [comment]
@sergeyf thank you! 

I've checked the results, and it looks that MLJAR can go even better by adding a Linear model. I've updated the MLJAR code and I'm computing the whole benchmark with the Linear model included in AutoML optimization. Let's wait 2 days for results ...

**Comment by sergeyf** [comment]
Sure. Just submit another PR to update the existing results instead of an
additional line to prevent crowding.

**Pull request merged**
